### ISSUE TITLE
json.decoder.JSONDecodeError: Extra data: line 1 column 2 (char 1)

### ISSUE THREAD

**Issue by changliucoding** [daswer123/Voyager_chekpoit#4]
Hi, when i tried to load the ckpt and made a diamondaxe I run into this issue 
Traceback (most recent call last):

File "f:\My_dir\Voyager\voyager\utils\json_utils.py", line 150, in fix_and_parse_json
File "f:\My_dir\Voyager\mc_port.py", line 23, in <module>
sub_goals = voyager.decompose_task(task=task)
File "f:\My_dir\Voyager\voyager\voyager.py", line 390, in decompose_task
return self.curriculum_agent.decompose_task(task, self.last_events)
File "f:\My_dir\Voyager\voyager\agents\curriculum.py", line 347, in decompose_task
return fix_and_parse_json(response)
File "f:\My_dir\Voyager\voyager\utils\json_utils.py", line 152, in fix_and_parse_json
json_str = correct_json(json_str)
File "f:\My_dir\Voyager\voyager\utils\json_utils.py", line 139, in correct_json
if balanced_str := balance_braces(json_str):
File "f:\My_dir\Voyager\voyager\utils\json_utils.py", line 101, in balance_braces
raise e
File "f:\My_dir\Voyager\voyager\utils\json_utils.py", line 98, in balance_braces
json.loads(json_string)
File "D:\miniconda3\envs\voyager_env\lib\json_init_.py", line 346, in loads
return _default_decoder.decode(s)
File "D:\miniconda3\envs\voyager_env\lib\json\decoder.py", line 340, in decode
raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 1 column 2 (char 1)

Wonder if you had the same issue before

**Comment by daswer123** [comment]
Honestly, I don't know, you'd better write to the developers in the official repo

**Comment by changliucoding** [comment]
> Honestly, I don't know, you'd better write to the developers in the official respo

still many thanks!
